---
stages:
  - pipeline_clean

image: dockerhub.timeweb.cloud/docker:dind

services:
  - name: dockerhub.timeweb.cloud/docker:dind
    alias: thedockerhost

variables:
  DOCKER_HOST: tcp://thedockerhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

pipeline:
  stage: pipeline_clean
  image: ghcr.io/rootshell-coder/xbash:latest
  before_script:
    - chmod +x ./cleaner.sh
  script:
    - ./cleaner.sh pipeline
...
