---
stages:
  - pipeline_clean
  - pipeline_making

image: ghcr.io/rootshell-coder/xbash:latest

services:
  - name: docker:dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

# Sedule clean task
pipeline:
  stage: pipeline_clean
  tags:
    - docker-runner
  script:
    - bash ./cleaner.sh pipeline
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never

# make id_proj.json create helper
making:
  stage: pipeline_making
  tags:
    - docker-runner
  script:
    - bash ./cleaner.sh making
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: manual
...
