---
name: xbash
on:
  schedule:
    - cron: "30 6 * * *"
  push:
    branches: ["master"]
    paths:
      - "docker/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["master"]
    paths:
      - "docker/**"
      - ".github/workflows/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: 5.2.26-alpine3.20
  VER_LOG: version_latest.txt

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build Test
        run: docker build -t ${{ env.REGISTRY }}/${{ github.repository }}:latest -f docker/Dockerfile .
